### ISSUE TITLE
zip64: TypeError on finalize

### ISSUE THREAD

**Issue by ctalkington** [ctalkington/node-compress-commons#12]
```
TypeError: Argument must be a string
    at Buffer.write (buffer.js:353:25)
    at ZipArchiveOutputStream._writeCentralFileHeader (/app/node_modules/archiver/node_modules/zip-stream/node_modules/compress-commons/lib/archivers/zip/zip-archive-output-stream.js:265:14)
    at null.<anonymous> (/app/node_modules/archiver/node_modules/zip-stream/node_modules/compress-commons/lib/archivers/zip/zip-archive-output-stream.js:118:10)
    at Array.forEach (native)
    at ZipArchiveOutputStream._finish (/app/node_modules/archiver/node_modules/zip-stream/node_modules/compress-commons/lib/archivers/zip/zip-archive-output-stream.js:117:17)
    at ArchiveOutputStream.finish (/app/node_modules/archiver/node_modules/zip-stream/node_modules/compress-commons/lib/archivers/archive-output-stream.js:105:8)
    at ZipStream.finalize (/app/node_modules/archiver/node_modules/zip-stream/lib/zip-stream.js:109:8)
    at Zip.finalize (/app/node_modules/archiver/lib/plugins/zip.js:34:15)
    at Archiver._moduleFinalize (/app/node_modules/archiver/lib/core.js:124:18)
    at Archiver._finalize (/app/node_modules/archiver/lib/core.js:89:8)
```
as reported on
ctalkington/node-archiver#120

**Comment by ctalkington** [comment]
cc @disbelief

**Comment by ctalkington** [comment]
pretty sure this traces back to

https://github.com/ctalkington/node-compress-commons/blob/0.2.1/lib/archivers/zip/zip-archive-output-stream.js#L265-L269

where its trying to write buffers to a buffer but buffer write only works with strings

**Comment by ctalkington** [comment]
@disbelief 0.2.2 has been released. this should fix that specific error. in regards to such sizes, zip64 needs testing but if you can provide feedback then we can get it ironed out. haven't had any such feedback yet.

**Comment by disbelief** [comment]
fantastic, @ctalkington 

I've dropped it into my application now. We deal with large files quite frequently so I'll let you know how it goes.

Thanks for the quick help with this, it's much appreciated!
