### ISSUE TITLE
Zip64 ReferenceError

### ISSUE THREAD

**Issue by disbelief** [ctalkington/node-compress-commons#13]
Hi @ctalkington, I've hit another exception that I believe is due to the zip64 instability you mentioned previously #12 

Here's the trace:

```
ReferenceError: ae is not defined
    at ZipArchiveOutputStream._writeCentralDirectoryZip64 (/app/node_modules/archiver/node_modules/zip-stream/node_modules/compress-commons/lib/archivers/zip/zip-archive-output-stream.js:217:37)
    at ZipArchiveOutputStream._finish (/app/node_modules/archiver/node_modules/zip-stream/node_modules/compress-commons/lib/archivers/zip/zip-archive-output-stream.js:124:10)
    at ArchiveOutputStream.finish (/app/node_modules/archiver/node_modules/zip-stream/node_modules/compress-commons/lib/archivers/archive-output-stream.js:105:8)
    at ZipStream.finalize (/app/node_modules/archiver/node_modules/zip-stream/lib/zip-stream.js:109:8)
    at Zip.finalize (/app/node_modules/archiver/lib/plugins/zip.js:34:15)
    at Archiver._moduleFinalize (/app/node_modules/archiver/lib/core.js:124:18)
    at Archiver._finalize (/app/node_modules/archiver/lib/core.js:89:8)
    at Archiver._onQueueDrain (/app/node_modules/archiver/lib/core.js:206:10)
    at next (/app/node_modules/async/lib/async.js:804:31)
    at Object._onImmediate (/app/node_modules/async/lib/async.js:32:16)
```

Let me know if you need any more info.

**Comment by ctalkington** [comment]
give v0.2.3 a go.

**Comment by disbelief** [comment]
Thanks dropped it in. Will report back with any problems.

**Comment by ctalkington** [comment]
@disbelief made a quick update to that after reviewing the flow the go lang uses for zip64

**Comment by disbelief** [comment]
Ah okay I saw the same error after dropping in v0.2.3. Nothing so far on 0.2.4. Thanks again!

**Comment by disbelief** [comment]
@ctalkington there's a typo at https://github.com/ctalkington/node-compress-commons/blob/master/lib/archivers/zip/zip-archive-output-stream.js#L238

`costants` should be `constants`

**Comment by ctalkington** [comment]
doh servers me right for trying to cram in edits between lunch

**Comment by ctalkington** [comment]
@disbelief ok v0.2.5 fixes that. do apologize for the issues. as you can prob tell i havent had the need to use zip64 and theres no good ways to test it currently with node unzip modules. its something that i was expecting to get user feedback on but no one ever had.

**Comment by disbelief** [comment]
Thanks @ctalkington and no worries re the issues. I'm overjoyed at how quickly you're able to knock them down.

Regarding Zip64, does that just kick in when the archive grows to a certain size, or is it entirely server-architecture-specific? We're making heavy use of ctalkington/node-archiver, and our users often zip up lots of files — frequently very large files too. Should be a good source of feedback! ;)

**Comment by ctalkington** [comment]
there are defined points when its required. usually:

sizes greater than 4GB
number of files greater than max int32

https://github.com/ctalkington/node-compress-commons/blob/master/lib/archivers/zip/zip-archive-output-stream.js#L421

https://github.com/ctalkington/node-compress-commons/blob/master/lib/archivers/zip/zip-archive-entry.js#L221

**Comment by disbelief** [comment]
ah I see. hence the difficultly in testing this stuff when dealing with such large numbers and file sizes.

**Comment by disbelief** [comment]
Me again. Instead of filing a new issue I'll just reopen this one since it's all zip64 stuff. Here's a new stack trace:

```
TypeError: Object [object Object] has no method 'getLongBytes'
    at ZipArchiveOutputStream._writeCentralDirectoryZip64 (/app/node_modules/archiver/node_modules/zip-stream/node_modules/compress-commons/lib/archivers/zip/zip-archive-output-stream.js:247:19)
    at ZipArchiveOutputStream._finish (/app/node_modules/archiver/node_modules/zip-stream/node_modules/compress-commons/lib/archivers/zip/zip-archive-output-stream.js:124:10)
    at ArchiveOutputStream.finish (/app/node_modules/archiver/node_modules/zip-stream/node_modules/compress-commons/lib/archivers/archive-output-stream.js:105:8)
    at ZipStream.finalize (/app/node_modules/archiver/node_modules/zip-stream/lib/zip-stream.js:109:8)
    at Zip.finalize (/app/node_modules/archiver/lib/plugins/zip.js:34:15)
    at Archiver._moduleFinalize (/app/node_modules/archiver/lib/core.js:124:18)
    at Archiver._finalize (/app/node_modules/archiver/lib/core.js:89:8)
    at Archiver._onQueueDrain (/app/node_modules/archiver/lib/core.js:206:10)
    at next (/app/node_modules/async/lib/async.js:804:31)
    at Object._onImmediate (/app/node_modules/async/lib/async.js:32:16)
```

**Comment by ctalkington** [comment]
man this function just didnt get much love from me!

**Comment by ctalkington** [comment]
v0.2.6 is now published. thanks again for the feedback.

**Comment by disbelief** [comment]
Thanks!!
